[colors.cursor]
cursor = "#3DFF00"
text = "#d8d8d8"

[colors.normal]
black = "#41464D"
blue = "#3971ED"
cyan = "#00DEFF"
green = "#2CCC00"
magenta = "#AB2EF9"
red = "#E10D00"
white = "#d8d8d8"
yellow = "#E0DB00"

[colors.primary]
background = "#000000"
foreground = "#c6c6c6"

[cursor]
blink_interval = 550
thickness = 0.25
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 14.0

[font.normal]
family = "monospace"

[selection]
save_to_clipboard = true

[window]
startup_mode = "Fullscreen"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 0
